### ISSUE TITLE
Why call this "AniSearch"?

### ISSUE THREAD

**Issue by Daijobou** [MrScopes/AniSearch#1]
Why do you call this "AniSearch" if it has nothing to do with Anime Database AniSearch?
https://www.anisearch.de/
https://www.anisearch.com/
https://www.anisearch.co.uk/

**Comment by MrScopes** [comment]
> Why do you call this "AniSearch" if it has nothing to do with Anime Database AniSearch?
> https://www.anisearch.de/
> https://www.anisearch.com/
> https://www.anisearch.co.uk/

I didn’t know it existed tbh, if they reach out to me I’ll rename

**Comment by MrScopes** [comment]
> Why do you call this "AniSearch" if it has nothing to do with Anime Database AniSearch?
> https://www.anisearch.de/
> https://www.anisearch.com/
> https://www.anisearch.co.uk/

I removed the org incase they want it, but I'm keeping the name "AniSearch"
